### ISSUE TITLE
npm run ionic:build fails

### ISSUE THREAD

**Issue by HansS** [javebratt/debtTracker#3]
ionic-hello-world@ ionic:serve C:\Users\Folio\web\firebase\debtTracker
> ionic-app-scripts serve

[18:07:21]  ionic-app-scripts 0.0.46
[18:07:21]  watch started ...
[18:07:21]  build dev started ...
[18:07:21]  clean started ...
[18:07:21]  clean finished in less than 1 ms
[18:07:21]  copy started ...
[18:07:21]  transpile started ...
[18:07:26]  build dev failed: Cannot read property 'indexOf' of undefined
[18:07:27]  copy: Error copying "C:\Users\Folio\web\firebase\debtTracker\node_modules\ionic-angular\fonts" to
            "C:\Users\Folio\web\firebase\debtTracker\www\assets\fonts"
[18:07:27]  copy finished in 5.12 s
[18:07:27]  watch ready in 5.17 s
[18:07:27]  dev server running: http://localhost:8100/

Batchvorgang abbrechen (J/N)? j

Folio@DESKTOP-960H438 C:\Users\Folio\web\firebase\debtTracker
> npm run ionic:build

> ionic-hello-world@ ionic:build C:\Users\Folio\web\firebase\debtTracker
> ionic-app-scripts build

[18:09:11]  ionic-app-scripts 0.0.46
[18:09:11]  build prod started ...
[18:09:11]  clean started ...
[18:09:11]  clean finished in 5 ms
[18:09:11]  copy started ...
[18:09:11]  ngc started ...
[18:09:11]  copy: Error copying "C:\Users\Folio\web\firebase\debtTracker\node_modules\ionicons\dist\fonts" to
            "C:\Users\Folio\web\firebase\debtTracker\www\assets\fonts"
[18:09:11]  copy finished in 162 ms
[18:09:28]  Error: Error at
            C:/Users/Folio/web/firebase/debtTracker/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:12:9
[18:09:28]  Duplicate identifier 'Promise'.
[18:09:28]  Error at
            C:/Users/Folio/web/firebase/debtTracker/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:17:9
[18:09:28]  Duplicate identifier 'Promise_Instance'.
[18:09:28]  Error at
            C:/Users/Folio/web/firebase/debtTracker/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:26:7
[18:09:28]  Cannot redeclare exported variable 'SDK_VERSION'.
[18:09:28]  Error at
            C:/Users/Folio/web/firebase/debtTracker/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:66:7
[18:09:28]  Cannot redeclare exported variable 'apps'.
[18:09:28]  Error at
            C:/Users/Folio/web/firebase/debtTracker/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:130:9

**Comment by javebratt** [comment]
You're not telling me anything, just pasting a bunch of terminal output doesn't help, what's going on? what kind of problem are you having? what are you doing when this breaks? etc... The more info you give the easier it is for me to help you.

**Comment by kyk000525** [comment]
Cannot find module "../pages/landing/langding"
hi that's what i got the errpr..
Error: Cannot find module "../pages/landing/langding"
    at eval (\C:\Users\User\finalproject\src\app\app.component.ts:5:7)
    at Object.<anonymous> (http://localhost:8100/build/main.js:4044:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (\C:\Users\User\finalproject\src\app\app.module.ts:3:73)
    at Object.<anonymous> (http://localhost:8100/build/main.js:3365:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at eval (\C:\Users\User\finalproject\src\app\main.dev.ts:2:70)
    at Object.<anonymous> (http://localhost:8100/build/main.js:4530:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:64:18

**Comment by javebratt** [comment]
This is un-related, but it's because you have a typo, it's not langding, it's landing.
